helm: ability to specify security context for pod
kubernetes-sigs/descheduler pull request #1311
Opened 2023-12-01 17:00 UTC by victorgs

This pull request adds the ability to specify the security context for the descheduler pod.

Other Kubernetes projects like the [cluster-autoscaler](https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/templates/deployment.yaml#L303-L305) has this ability, useful to define the `fsGroup` setting which is only available at the pod level.

I tested it doing the change below and installing the helm chart in a kind cluster to be sure the schema is valid:
```diff
diff --git a/charts/descheduler/values.yaml b/charts/descheduler/values.yaml
index afc3b8ca3..d47c0a581 100644
--- a/charts/descheduler/values.yaml
+++ b/charts/descheduler/values.yaml
@@ -33,8 +33,8 @@ securityContext:
   runAsUser: 1000

 # podSecurityContext -- [Security context for pod](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
-podSecurityContext: {}
-  # fsGroup: 1000
+podSecurityContext:
+  fsGroup: 1000

 nameOverride: ""
 fullnameOverride: ""
```

The pods running has the `fsGroup` set:
```
~/src/descheduler pod-security-context !1 ❯ k get pod descheduler-28357494-4snw7 -o yaml|grep fsGroup                                                                                        

fsGroup: 1000
```

2023-12-02 05:21 UTC, a7i requested changes

2023-12-02 05:21 UTC, a7i commented on charts/descheduler/templates/deployment.yaml
> +        {{- .Values.podSecurityContext | toYaml | nindent 12 }}
```suggestion
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
```

2023-12-02 05:22 UTC, a7i commented on charts/descheduler/templates/cronjob.yaml
> +            {{- .Values.podSecurityContext | toYaml | nindent 12 }}
to be consistent:
```suggestion
        {{- toYaml .Values.podSecurityContext | nindent 12 }}
```

2023-12-02 13:56 UTC, a7i commented
/ok-to-test
/label tide/merge-method-squash

2023-12-05 03:35 UTC, a7i commented
/lgtm

2023-12-05 03:36 UTC, a7i commented
Thank you for your contribution @victorgs  🏆

2023-12-05 03:40 UTC, merged

2023-12-05 12:16 UTC, victorgs commented
Thank you Amir! < 3