EnableFullEviction for RemovePodsViolatingNodeAffinity
kubernetes-sigs/descheduler pull request #1363
Opened 2024-03-07 20:55 UTC by jackfrancis

This PR adds a `EnableFullEviction` configuration option to the `RemovePodsViolatingNodeAffinity` plugin. Enabling it would look like this:

```yaml
apiVersion: v1
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: ProfileName
        pluginConfig:
        - name: "RemovePodsViolatingNodeAffinity"
          args:
            nodeAffinityType:
            - "requiredDuringSchedulingIgnoredDuringExecution"
            enableFullEviction: true
        plugins:
          deschedule:
            enabled:
              - "RemovePodsViolatingNodeAffinity"
```

The purpose of this feature is to enable eviction of all pod replicas whose declared nodeAffinity configuration no longer matches the node they are currently scheduled onto, _even if there is no other node in the cluster that has a nodeAffinity match_. That last part (in italics) is the change that I'm advocating for here.

TODO: docs and updated helm chart

2024-03-07 21:08 UTC, jackfrancis commented
Here's a quick overview of this feature in action (built an image from this branch and smoke-tested it on a Cluster API CAPZ cluster in Azure).

A watch stream of pod replicas that have a "foo=bar" nodeAffinity (`requiredDuringSchedulingIgnoredDuringExecution`) nodeSelector match config:

```sh
$ k get pods -l run=php-apache -o wide -w
NAME                          READY   STATUS    RESTARTS   AGE   IP       NODE     NOMINATED NODE   READINESS GATES
php-apache-7674886bb6-89mxt   0/1     Pending   0          10m   <none>   <none>   <none>           <none>
php-apache-7674886bb6-cjfpb   0/1     Pending   0          10m   <none>   <none>   <none>           <none>
php-apache-7674886bb6-x5b54   0/1     Pending   0          10m   <none>   <none>   <none>           <none>
php-apache-7674886bb6-89mxt   0/1     Pending   0          11m   <none>   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-x5b54   0/1     Pending   0          11m   <none>   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-cjfpb   0/1     Pending   0          11m   <none>   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-89mxt   0/1     ContainerCreating   0          11m   <none>   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-cjfpb   0/1     ContainerCreating   0          11m   <none>   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-x5b54   0/1     ContainerCreating   0          11m   <none>   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-89mxt   0/1     ContainerCreating   0          11m   <none>   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-cjfpb   0/1     ContainerCreating   0          11m   <none>   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-x5b54   0/1     ContainerCreating   0          11m   <none>   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-x5b54   1/1     Running             0          11m   192.168.91.136   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-89mxt   1/1     Running             0          11m   192.168.91.134   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-cjfpb   1/1     Running             0          11m   192.168.91.135   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-89mxt   1/1     Running             0          11m   192.168.91.134   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-89mxt   1/1     Terminating         0          11m   192.168.91.134   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-52dwx   0/1     Pending             0          0s    <none>           <none>                            <none>           <none>
php-apache-7674886bb6-x5b54   1/1     Running             0          11m   192.168.91.136   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-89mxt   1/1     Terminating         0          11m   192.168.91.134   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-52dwx   0/1     Pending             0          0s    <none>           capz-e2e-rqyahs-vmss-mp-0000004   <none>           <none>
php-apache-7674886bb6-x5b54   1/1     Terminating         0          11m   192.168.91.136   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-slknb   0/1     Pending             0          0s    <none>           <none>                            <none>           <none>
php-apache-7674886bb6-x5b54   1/1     Terminating         0          11m   192.168.91.136   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-cjfpb   1/1     Running             0          11m   192.168.91.135   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-slknb   0/1     Pending             0          0s    <none>           capz-e2e-rqyahs-vmss-mp-0000003   <none>           <none>
php-apache-7674886bb6-52dwx   0/1     ContainerCreating   0          0s    <none>           capz-e2e-rqyahs-vmss-mp-0000004   <none>           <none>
php-apache-7674886bb6-cjfpb   1/1     Terminating         0          11m   192.168.91.135   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-slknb   0/1     ContainerCreating   0          0s    <none>           capz-e2e-rqyahs-vmss-mp-0000003   <none>           <none>
php-apache-7674886bb6-8fdtg   0/1     Pending             0          0s    <none>           <none>                            <none>           <none>
php-apache-7674886bb6-cjfpb   1/1     Terminating         0          11m   192.168.91.135   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-8fdtg   0/1     Pending             0          0s    <none>           capz-e2e-rqyahs-vmss-mp-0000004   <none>           <none>
php-apache-7674886bb6-8fdtg   0/1     ContainerCreating   0          0s    <none>           capz-e2e-rqyahs-vmss-mp-0000004   <none>           <none>
php-apache-7674886bb6-89mxt   1/1     Terminating         0          11m   192.168.91.134   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-x5b54   1/1     Terminating         0          11m   192.168.91.136   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-cjfpb   1/1     Terminating         0          11m   192.168.91.135   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-89mxt   0/1     Terminating         0          11m   <none>           capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-x5b54   0/1     Terminating         0          11m   <none>           capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-slknb   0/1     ContainerCreating   0          0s    <none>           capz-e2e-rqyahs-vmss-mp-0000003   <none>           <none>
php-apache-7674886bb6-cjfpb   0/1     Terminating         0          11m   <none>           capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-8fdtg   0/1     ContainerCreating   0          0s    <none>           capz-e2e-rqyahs-vmss-mp-0000004   <none>           <none>
php-apache-7674886bb6-52dwx   0/1     ContainerCreating   0          1s    <none>           capz-e2e-rqyahs-vmss-mp-0000004   <none>           <none>
php-apache-7674886bb6-89mxt   0/1     Terminating         0          11m   192.168.91.134   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-89mxt   0/1     Terminating         0          11m   192.168.91.134   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-89mxt   0/1     Terminating         0          11m   192.168.91.134   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-cjfpb   0/1     Terminating         0          11m   192.168.91.135   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-cjfpb   0/1     Terminating         0          11m   192.168.91.135   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-cjfpb   0/1     Terminating         0          11m   192.168.91.135   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-8fdtg   1/1     Running             0          1s    192.168.54.134   capz-e2e-rqyahs-vmss-mp-0000004   <none>           <none>
php-apache-7674886bb6-x5b54   0/1     Terminating         0          11m   192.168.91.136   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-x5b54   0/1     Terminating         0          11m   192.168.91.136   capz-e2e-rqyahs-vmss-mp-0000002   <none>           <none>
php-apache-7674886bb6-x5b54   0/1     Terminating         0          11m   192.168.91.136   capz-e2e-rqyahs-vmss-mp-0000002   < [...]

2024-03-08 13:38 UTC, damemi requested changes
if we were to do something like this, I would rather see it as an option in something like NodeFit, or somewhere more general since this same logic could apply to other strategies like taints and inter pod affinity.

I also would give this a more descriptive name like `EvictWithoutFit` or something that makes it clear that this will likely just put pods into a Pending state. I understand that is the goal, but what is the use case for this? I'm curious what your scenario is that it's preferable to end up with all the pods stuck Pending. Maybe there is another avenue we could explore that better suits your needs?

2024-03-08 16:10 UTC, jackfrancis commented
@damemi thanks for the detailed feedback. I actually agree that this would be ideal in a more general area, I'll scaffold that up to see how it looks.

Here's my use-case: in a multi-cluster environment, I'd like to be able to leverage descheduler as a trigger to indicate when a workload no longer has any suitable node to run on according to its requirements (e.g., nodeSelector, taints). More specifically:

- Some multi-cluster-aware scheduler continually watches workloads on specific clusters and evaluates whether or not they are in a durably stable state
  - As an example, are < 100% of pod replicas in a non-Running state beyond some TTL?
- When a workload is deemed to be unreliable on the cluster its scheduled onto, the multi-cluster-aware scheduler will reschedule that workload to _another_ cluster in its multi-cluster fleet.

And so, the current default descheduler behavior can prevent the above for a simple scenario where there are a small number of pod replicas able to fit onto a single node.

1. node attributes change over time
2. descheduler notices that pod scheduling criteria is no longer met on already scheduled pods running on nodes whose attributes are changing
3. pods move to other nodes that do meet that criteria
4. when no nodes on the cluster meet the criteria at all do to continued cluster node entropy, currently Running pods continue Running indefinitely as descheduler is no longer allowed to do anything

So from a high level, I'd like to be able to leverage descheduler to definitely signal (via all pods in a non-Running state) that a cluster no longer has any suitable nodes to run my workload, so that I can move those workloads to another cluster.

2024-03-12 17:58 UTC, ingvagabund commented
+1 for making the configuration part of NodeFit to e.g disable the check.

2024-10-28 12:29 UTC, closed without merging