Release v1.19 Helm chart rename - Step #2
kubernetes-sigs/descheduler pull request #459
Opened 2020-12-08 18:44 UTC by stevehipwell

2020-12-08 19:09 UTC, stevehipwell commented
/assign @damemi

2020-12-08 19:16 UTC, damemi commented
/hold
for steps 1 & 2

2020-12-08 19:29 UTC, damemi commented on README.md
> +- Some nodes are under or over utilized.
There's a lot of odd updates to the README.md in this PR, are these intentional or maybe an editor auto-formatting? Would like to undo these if possible

2020-12-08 19:37 UTC, damemi requested changes
looks like steps 1 & 2 worked out, the index.yaml is getting updated and the 1.18 release still the right naming scheme, so I think we can keep going with this PR

@stevehipwell thanks again for your help so far, could you just revert the changes in this PR to README.md? It seems like they were unintentional

2020-12-08 19:50 UTC, damemi commented
/ok-to-test

2020-12-08 20:04 UTC, stevehipwell commented
@damemi I made a change in the README but it looks like my formatter tidied it up too. I'm not by my machine at the moment so is it possible to take the change or do I need to update the PR? This is time sensitive as v0.19 will be missing from the hub so if I need to I can get back to my machine.

2020-12-08 20:10 UTC, damemi commented
@stevehipwell I suppose those changes aren't a big problem, and it does correct some formatting that was messed up (like extra backtics in code blocks)

Since this is time sensitive, I'm fine merging the changes in formatting now too.
/hold cancel

Once this merges, please check that everything looks good on your end too and let us know. Thank you!

2020-12-08 20:13 UTC, damemi commented
/approve
/lgtm

2020-12-08 20:15 UTC, merged

2020-12-08 20:18 UTC, stevehipwell commented
@damemi this all looks good to me.

2020-12-08 21:12 UTC, stevehipwell commented
@damemi it looks like the GitHub release action has failed for the v0.19 release.

2020-12-08 21:49 UTC, damemi commented
@stevehipwell thanks, looks like a CI check was blocking it. Re-ran and it looks like it completed

2020-12-08 22:12 UTC, stevehipwell commented
@damemi I think you either need to delete the `descheduler-helm-chart-0.19.2` tag and then re run the action or manually modify the _index.yaml_ file on the `gh-pages` branch; as it looks like the failure wasn't cleaned up correctly so resulted in a NOP.

2020-12-09 01:50 UTC, damemi commented
@stevehipwell oh, that makes sense. I was able to delete the branch/release and re-run the job. The right version appears to be in index.yaml now: https://github.com/kubernetes-sigs/descheduler/blob/97a0ab9/index.yaml

and the release is back https://github.com/kubernetes-sigs/descheduler/releases/tag/descheduler-helm-chart-0.19.2

If you can double check that I got this right and I'm not missing anything else that would be great!

2020-12-09 07:12 UTC, stevehipwell commented
@damemi I can now see the v0.19 chart on artifacthub.io so it looks good to me.