Add option to ignore pods with PVCs from eviction
kubernetes-sigs/descheduler pull request #481
Opened 2021-01-11 16:19 UTC by damemi

Fixes https://github.com/kubernetes-sigs/descheduler/issues/96

2021-01-11 16:19 UTC, damemi commented
/hold
`make gen` is currently broken due to the logging fields

2021-01-11 19:46 UTC, damemi reviewed
/hold cancel
make gen is fixed now

2021-01-12 20:40 UTC, damemi commented
/kind feature

2021-01-18 14:42 UTC, ingvagabund requested changes
Can you add a test case for the new flag? In any of the strategies you choose.

Wrt. `ignore` prefix, we already have `ExcludeOwnerKinds` and `Exclude` namespaces fields. Do you think it would make sense to align the new field with existing ones? I.e. `excludePVCPods`? Even `IgnorePVCPods` sounds ok to me.

2021-01-18 14:42 UTC, ingvagabund commented on cmd/descheduler/app/options/options.go
> +
You can drop the additional line

2021-01-18 15:29 UTC, lixiang233 reviewed
Besides, we should update the [user guide](https://github.com/kubernetes-sigs/descheduler/blob/master/docs/user-guide.md) to include the new flag

2021-01-25 19:29 UTC, damemi commented
Updated this to remove the extra line and added the flag to readme

2021-01-26 11:02 UTC, ingvagabund commented
Unit test please

2021-01-26 13:48 UTC, damemi commented
Sorry, forgot the unit test. Added to `PodLifeTime`

2021-01-27 06:41 UTC, lixiang233 approved these changes
/lgtm

2021-01-27 06:41 UTC, merged

2021-05-06 10:02 UTC, jsravn commented
Minor nit: could we rename the option from `ignorePvcPods` to `evictPvcPods` before this is released? I found the option name confusing - I took it to mean "ignore PVCs when considering a pod for eviction", rather than "ignore pods with PVCs when evicting".

2021-05-06 14:28 UTC, damemi commented
Hi @jsravn, thanks for the feedback. The motivation behind naming this `ignorePvcPods` was the the current default Descheduler behavior is to evict Pvc Pods. So, rather than add the new flag with a default value `true`, we added it so that it semantically defaults to `false`, preserving the existing default behavior without any change to behavior.

I hope this clears up the confusion. At this point, I would personally prefer not to make that change since it would be a full invert of the behavior. However if others disagree I am open to the consideration