(TopologySpread) Evict pods with selectors that match multiple nodes
kubernetes-sigs/descheduler pull request #525
Opened 2021-03-11 15:05 UTC by damemi

Fixes https://github.com/kubernetes-sigs/descheduler/issues/524

2021-03-11 15:06 UTC, damemi reviewed
/cc @seanmalloy @ingvagabund

2021-03-11 18:31 UTC, uthark approved these changes

2021-03-12 08:37 UTC, ingvagabund commented on pkg/descheduler/strategies/topologyspreadconstraint.go
> -			if aboveToEvict[k].Spec.NodeSelector != nil ||
Can you break the changes into two steps?
1. create `isRequiredDuringSchedulingIgnoredDuringExecution = aboveToEvict[k].Spec.Affinity != nil && aboveToEvict[k].Spec.Affinity.NodeAffinity != nil && aboveToEvict[k].Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution != nil` variable so it's easier to read the condition
2. fix the bug

In which case the change will look like:

```go
aboveToEvict[k].Spec.NodeSelector != nil ||
(
	isRequiredDuringSchedulingIgnoredDuringExecution &&
	nodesPodFitsOnBesidesCurrent(aboveToEvict[k], nodeMap) == 0
)
```
-->
```go
(
	aboveToEvict[k].Spec.NodeSelector != nil || isRequiredDuringSchedulingIgnoredDuringExecution
) &&
nodesPodFitsOnBesidesCurrent(aboveToEvict[k], nodeMap) == 0
```

After which it's clear why the change is required.

2021-03-12 08:39 UTC, ingvagabund requested changes
Small change to improve the readability

2021-03-12 19:09 UTC, damemi commented
Thanks @ingvagabund, updated

2021-03-14 09:33 UTC, ingvagabund commented
/lgtm

2021-03-14 09:35 UTC, merged