Add node name label to the counter metric for evicted pods
kubernetes-sigs/descheduler pull request #670
Opened 2021-12-09 13:52 UTC by autumn0207

Add node name label to improve pod eviction metrics.

2021-12-09 13:55 UTC, damemi reviewed
/ok-to-test
@autumn0207 thanks, you'll also need to sign the CLA

2021-12-10 00:38 UTC, autumn0207 commented
/retest

<br class="Apple-interchange-newline">

2021-12-10 00:55 UTC, autumn0207 commented
> /ok-to-test @autumn0207 thanks, you'll also need to sign the CLA

Thanks for reminding me. I have signed it now.

2021-12-10 02:23 UTC, autumn0207 commented
/assign @damemi
/assign @ingvagabund

2021-12-15 12:33 UTC, ingvagabund requested changes

2021-12-15 12:33 UTC, ingvagabund commented on metrics/metrics.go
>  		}, []string{"result", "strategy", "namespace"})
This list needs to be extended as well

2021-12-16 03:47 UTC, autumn0207 commented on metrics/metrics.go
>  		}, []string{"result", "strategy", "namespace"})
ok, I have fixed it~

2021-12-16 04:38 UTC, autumn0207 commented
/assign @ingvagabund

2021-12-16 08:54 UTC, ingvagabund commented
Thank You. Can you also squash the commits?

2021-12-16 09:11 UTC, autumn0207 commented
> Thank You. Can you also squash the commits?

sure, already done

2021-12-16 09:47 UTC, ingvagabund commented
/approve
/lgtm

2021-12-16 09:49 UTC, merged