feat: Add DeviationThreshold Paramter for LowNodeUtilization, (Previous attempt - #473 )
kubernetes-sigs/descheduler pull request #751
Opened 2022-03-01 13:40 UTC by HelmutLety

This is duplicate of #473 
Because the last PR was done over a year ago, the code-base has changed a lot, it was easier to do a new PR.

Thanks to @AmoVanB, 

https://github.com/kubernetes-sigs/descheduler/pull/473#issue-769030153

2022-03-01 20:45 UTC, damemi reviewed
/ok-to-test
@HelmutLety thanks for picking this back up. I'll try to take a look at this soon if someone else doesn't get to it first.

In the mean time, you'll also need to sign the CLA (check the bot comment for a link). Thanks!

2022-03-02 06:55 UTC, HelmutLety commented
/retest
cool, thanks @damemi

2022-03-02 08:22 UTC, HelmutLety commented
/retest

2022-03-11 13:41 UTC, ingvagabund requested changes
Would you mind rebasing your PR on top of https://github.com/kubernetes-sigs/descheduler/pull/762? The `getNodeUsage` function is not the right place for computing any threshold. I have moved the computation under new `getNodeThresholds`.

2022-03-11 13:41 UTC, ingvagabund commented on pkg/descheduler/strategies/nodeutilization/nodeutilization.go
> +	var averageCPUUsagePercent float64
`averageResourceUsagePercent := map[v1.ResourceName]float64{}` will allow to iterate over resources (including the extended ones)

2022-03-11 13:41 UTC, ingvagabund commented on pkg/descheduler/strategies/nodeutilization/nodeutilization.go
> +func getResourceNames(thresholds api.ResourceThresholds) (resourceNames []v1.ResourceName) {
`thresholds` is expected to have all the resources listed. Including CPU, Memory and Pods. No need to extent the function with those.

2022-03-11 13:41 UTC, ingvagabund commented on pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
> +	if !useDeviationThresholds {
`thresholds` and `targetThresholds` have to be set for all three CPU, memory and pods resources in every case. The default value in the `useDeviationThresholds` case is 0 (`MinResourcePercentage`). Which will help to transform:
```
if _, ok := lowThreshold[v1.ResourcePods]; !ok {
	lowResourceThreshold[v1.ResourcePods] = nodeCapacity.Pods()
	highResourceThreshold[v1.ResourcePods] = nodeCapacity.Pods()
} else {
	lowResourceThreshold[v1.ResourcePods] = resource.NewQuantity(int64(normalizeResourcePercentage(averagePodsUsagePercent-float64(lowThreshold[v1.ResourcePods]))*float64(nodeCapacity.Pods().Value())*0.01), resource.DecimalSI)
	highResourceThreshold[v1.ResourcePods] = resource.NewQuantity(int64(normalizeResourcePercentage(averagePodsUsagePercent+float64(highThreshold[v1.ResourcePods]))*float64(nodeCapacity.Pods().Value())*0.01), resource.DecimalSI)
}
```
into
```
if lowThreshold[v1.ResourcePods] == MinResourcePercentage {
	lowResourceThreshold[v1.ResourcePods] = nodeCapacity.Pods()
	highResourceThreshold[v1.ResourcePods] = nodeCapacity.Pods()
} else {
	lowResourceThreshold[v1.ResourcePods] = resource.NewQuantity(int64(normalizeResourcePercentage(averagePodsUsagePercent-float64(lowThreshold[v1.ResourcePods]))*float64(nodeCapacity.Pods().Value())*0.01), resource.DecimalSI)
	highResourceThreshold[v1.ResourcePods] = resource.NewQuantity(int64(normalizeResourcePercentage(averagePodsUsagePercent+float64(highThreshold[v1.ResourcePods]))*float64(nodeCapacity.Pods().Value())*0.01), resource.DecimalSI)
}
```

2022-03-16 14:45 UTC, HelmutLety commented
/easycla

2022-03-16 14:46 UTC, HelmutLety commented
/retest

2022-03-17 10:29 UTC, HelmutLety commented
Fighting with EasyCLA over, all good now :tada:

2022-03-24 13:02 UTC, ingvagabund commented on pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
> +			useDeviationThresholds: false,
`false` is the default value, no need to set `useDeviationThresholds` explicitly. The same for other occurrences.

2022-03-24 13:02 UTC, ingvagabund commented on pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
> +			thresholds:             api.ResourceThresholds{v1.ResourceCPU: 30, v1.ResourcePods: 30},
Would you mind putting back the original formatting? I.e. `api.ResourceThresholds{v1.ResourceCPU: 30, v1.ResourcePods: 30},` into:
```
api.ResourceThresholds{
	v1.ResourceCPU: 30,
	v1.ResourcePods: 30,
},
```
The same for other occurrences.

2022-03-24 13:03 UTC, ingvagabund requested changes
Few nits to address. Looks good in overall now.

2022-03-25 10:55 UTC, HelmutLety commented on pkg/descheduler/strategies/nodeutilization/nodeutilization.go
> +		for ressource, value := range usage {
done

2022-03-25 10:56 UTC, HelmutLety commented on pkg/descheduler/strategies/nodeutilization/nodeutilization.go
> +					nodeThresholdsMap[node.Name].lowResourceThreshold[resourceName] = resourceThreshold(nodeCapacity, resourceName, averageResourceUsagePercent[resourceName]-lowThreshold[resourceName])
I introduced the function `normalizePercentage(percent api.Percentage) api.Percentage` for that in my last commit

2022-03-25 11:00 UTC, HelmutLety commented
thanks @ingvagabund ! I made all the changes. If you could have a look at my last commit, would be cool

2022-03-28 10:04 UTC, ingvagabund commented
@HelmutLety if you could squash the commits before the final approve/lgtm

2022-03-28 10:38 UTC, HelmutLety commented
@ingvagabund yes, done

2022-03-28 10:52 UTC, ingvagabund commented
@HelmutLety much appreciated picking up and finishing the work @AmoVanB started. Than You both!!!

/approve
/lgtm

2022-03-28 10:53 UTC, merged